Chapter2
AriBram/DataDevOps pull request #2
Opened 2021-12-08 21:07 UTC by AriBram

2021-12-08 21:07 UTC, AriBram commented
@tsukabris прошу проверить выполнение дз

2021-12-14 11:33 UTC, Tsukabris commented on hw2/part1.md
> +
А где решение?

2021-12-14 11:34 UTC, Tsukabris requested changes
Кроме отсутствия первой задачи всё сделано красиво и правильно.

2021-12-14 12:58 UTC, AriBram commented on hw2/part1.md
> +
У меня возникли определенные трудности с пониманием задачи, а для вопросов было уже поздно, дедлайн подходил.

Исходя из условий, я понял что нужно скопировать часть мануала в отдельный файл, видимо воспользовавшись функционалом Vim (поправьте, если ошибаюсь). Эта часть в моем представлении начинается с " Variable names with special meanings: " (в этом у меня тоже есть сомнения). И заканчивается после перечисления переменных. 

Решение мне представляется как :  
- открыть в vim мануал и пустой файл, 
- перейти на строку в мануале с которой начинается раздел,
- командой скопировать n-е количество строк, видимо определяемое на глаз,
- перейти к другому файлу и вставить текст
- сохранить изменения

Это решение мне показалось немного сумбурным, поэтому я решил сначала разъяснить непонятные мне моменты. Если вам несложно, напишите свои мысли по поводу выше изложенного.

2021-12-16 13:35 UTC, AriBram commented
@Tsukabris мне делать мёрж или что-нибудь добавить?

2021-12-21 16:44 UTC, merged