Chapter4
AriBram/DataDevOps pull request #3
Opened 2021-12-15 18:27 UTC by AriBram

2021-12-15 18:29 UTC, AriBram commented
У меня проблемы с интернетом, поэтому не знаю, успею ли доделать третью задачу вовремя.
@Cakemanator прошу проверить то, что сделано, как появится возможность, докину решение 3-й задачи

2021-12-15 20:58 UTC, AriBram commented
Вроде успел до дедлайна

2021-12-16 07:55 UTC, Cakemanator requested changes

2021-12-16 07:55 UTC, Cakemanator commented on hw4/task3.md
> +
Можно добавить проверку, что пользователи могут/не могут заходить/читать/писать в эти директории?

2021-12-16 14:52 UTC, Cakemanator commented on hw4/task3.md
> +[user1@localhost ~]$ sudo setfacl -m u:jones:rx /share/cases
Если в директории появится новый файл, к нему применится указанный acl?

2021-12-17 12:58 UTC, Cakemanator approved these changes

2021-12-17 14:11 UTC, merged